### ISSUE TITLE
UX issue on Mangata DEX

### ISSUE THREAD

**Issue by dot-alert** [mangata-finance/mangata-sdk#45]
Hello,

I don't see the repository for the MangataDEX in your GitHub, so I'm putting this issue here.

The UI for depositing TUR tokens on MangataDEX displays all tokens held by the account, including *locked* tokens. 
When the user attempts to deposit his/her entire balance into MangataDEX, s/he gets a confirmation message that the transfer is done, but the XC transfer does **not** actually go through (i.e locked tokens are not transferrable).  There is no message on the screen advising users that the transfer failed.  

![Mangata1](https://user-images.githubusercontent.com/112253893/188053862-bf096ada-572e-4224-8841-3f4c680b7aec.JPG)

![Mangata1b](https://user-images.githubusercontent.com/112253893/188053887-29257937-aacc-4259-8c57-b6240adb1675.JPG)

Please look into this issue ASAP so that ONLY transferrable tokens are shown in your UI. This will help users avoid repeating the operation again and again, losing some of their balance in fees (0.55+ TUR per transaction!) in the process.

Thanks.

**Comment by dot-alert** [comment]
Addendum: 
When withdrawing TUR tokens, there is no confirmation message for the transaction, yet the transaction goes through and tokens and sent back to the account.

Please look into this issue ASAP, for security purposes.

**Comment by devdanco** [comment]
Hi @dot-alert thank you for raising this issue. Our DEX repo will be soon open source.

And yes you are absolutely right this we need to show only transferable tokens not all. We will fix this ASAP.

Regarding withdrawing TUR tokens. The only confirmation we can give the user is that his funds will be transfer to his account. We give user confirmation that it takes roughly two minutes to see his funds. With current XCM we can only see events but those events are not associated with the account who send it therefore we only show that he needs to wait two minutes.

Again thank you raising this issue. We will let you know once it is solved.

**Comment by dot-alert** [comment]
> Regarding withdrawing TUR tokens. The only confirmation we can give the user is that his funds will be transfer to his account. We give user confirmation that it takes roughly two minutes to see his funds. With current XCM we can only see events but those events are not associated with the account who send it therefore we only show that he needs to wait two minutes.

Thanks for the fast reply! 
FYI, this 👇🏿 is what I got on screen when I pressed the button to withdraw TUR from MangataDEX:
![Mangata2](https://user-images.githubusercontent.com/112253893/188071366-69a227c4-3d90-44f8-a469-f94216628851.JPG)

However, I never got a Talisman modal/pop-up that allows me to **APPROVE** this transaction. I also never got the user confirmation message, as the UI froze up. Yet, **the transaction still went ahead**. 😅

Granted, it could have just been a one-off thing. But I just needed to let you know about this occurrence, so you can review your code and check that everything is in place. 

Cheers! 👌🏿

**Comment by devdanco** [comment]
This could be when we did something unexpected because there were lot of releases or our block production was slow and sometimes it may cause this issue. But it should be only one time thing. 

Anyway thank you for raising those issue. Our devs are already working on those locked tokens

**Comment by devdanco** [comment]
Hi @dot-alert I forgot to write here that the issue regarding frozen tokens on deposit was solved.
